# Generated by Django 4.1.5 on 2023-04-08 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_category_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
