# Generated by Django 4.1.5 on 2023-04-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('resim', models.FileField(blank=True, null=True, upload_to='afis', verbose_name='Afis Resmi')),
            ],
        ),
    ]
